# NumPy

## Завдання 1

- Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
- Виведіть вихідний масив.
- Запитайте у користувача число (порогове значення).
- Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
- Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
- Відсортуйте масив за спаданням і виведіть відсортований масив.

In [2]:
import numpy as np

In [4]:
# Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
# Виведіть вихідний масив.
arr1 = np.random.randint(0, 51, size=20)
print(arr1)

[15 48 36 17  8 11 22 31 39  2 41 30 36 13 13 39  4 24 45 24]


In [13]:
# Запитайте у користувача число (порогове значення).
usersNum = int(input("Enter threshold value:"))

Enter threshold value: 20


In [15]:
# Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
sumHigherThanUsersNum = sum(1 for num in arr1 if num > usersNum)
print(sumHigherThanUsersNum)

12


In [18]:
# Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
MaxValueOfArr1 = max(arr1)
print("Max value:", MaxValueOfArr1)
print("First appearance index: ", np.where(arr1 == MaxValueOfArr1)[0])

Max value: 48
First appearance index:  [1]


In [20]:
# Відсортуйте масив за спаданням і виведіть відсортований масив.
print(np.sort(arr1)[::-1])

[48 45 41 39 39 36 36 31 30 24 24 22 17 15 13 13 11  8  4  2]


## Завдання 2

- Запитайте в користувача верхню та нижню межу діапазону чисел.
- Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
- Виведіть вихідну матрицю.
- Отримайте головну діагональ і виведіть діагональні елементи.
- Підрахуйте суму елементів головної діагоналі та виведіть результат.
- Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [23]:
# Запитайте в користувача верхню та нижню межу діапазону чисел.
topLimit = int(input("Enter top Limit:"))
bottomLimit = int(input("Enter bottom Limit:"))


Enter top Limit: 20
Enter bottom Limit: 1


In [29]:
# Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
# Виведіть вихідну матрицю.
arr2 = np.random.randint(bottomLimit+1, topLimit, size=(5,5))
print(arr2)

[[ 2 14  7 16  3]
 [17 13  4 19  3]
 [17 17 15 15  4]
 [12 15 12  2  6]
 [ 6  9  3  8 12]]


In [32]:
# Отримайте головну діагональ і виведіть діагональні елементи.
primaryDiag = np.diag(arr2)
primaryDiag

array([ 2, 13, 15,  2, 12], dtype=int32)

In [34]:
# Підрахуйте суму елементів головної діагоналі та виведіть результат.
sum(primaryDiag)

np.int32(44)

In [35]:
# Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.
np.tril(arr2)

array([[ 2,  0,  0,  0,  0],
       [17, 13,  0,  0,  0],
       [17, 17, 15,  0,  0],
       [12, 15, 12,  2,  0],
       [ 6,  9,  3,  8, 12]], dtype=int32)

## Завдання 3

- Запитайте у користувача початок і кінець діапазону чисел.
- Сформуйте послідовність цілих чисел у вказаному діапазоні.
- Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
- Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
- Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [37]:
# Запитайте у користувача початок і кінець діапазону чисел.
topLimit = int(input("Enter top Limit:"))
bottomLimit = int(input("Enter bottom Limit:"))

Enter top Limit: 100
Enter bottom Limit: 0


In [45]:
# Сформуйте послідовність цілих чисел у вказаному діапазоні.
arr3 = np.random.randint(bottomLimit, topLimit+1, size=30)
arr3

array([29, 36,  0, 23, 46,  7, 75, 11, 35, 22, 15, 25, 65, 89, 39, 36, 67,
       32, 99, 69, 72, 62, 53, 44, 70, 10, 65, 85, 78, 61], dtype=int32)

In [47]:
# Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
arr3 = np.reshape(arr3, shape=(6, 5))
arr3

array([[29, 36,  0, 23, 46],
       [ 7, 75, 11, 35, 22],
       [15, 25, 65, 89, 39],
       [36, 67, 32, 99, 69],
       [72, 62, 53, 44, 70],
       [10, 65, 85, 78, 61]], dtype=int32)

In [48]:
# Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
print(np.sum(arr3, axis=1))

[134 150 233 303 301 299]


In [50]:
# Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.
print(np.max(arr3, axis=0))

[72 75 85 99 70]


## Завдання 4

- Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
- Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
- Виведіть вихідний масив.
- Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
- Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
- Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.

In [52]:
# Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
topLimit = int(input("Enter top Limit (including negative numbers):"))
bottomLimit = int(input("Enter bottom Limit (including negative numbers):"))

Enter top Limit (including negative numbers): 20
Enter bottom Limit (including negative numbers): -20


In [53]:
# Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
# Виведіть вихідний масив.
arr4 = np.random.randint(bottomLimit, topLimit+1, size=15)
arr4

array([-19,  19, -14,  -6,  -9,   6,   2,  17,  12, -13,  20, -19, -10,
         7,  -9], dtype=int32)

In [58]:
# Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
negativeArr4 = []
for num in arr4:
    if num < 0:
        negativeArr4.append(num)
negativeArr4

[np.int32(-19),
 np.int32(-14),
 np.int32(-6),
 np.int32(-9),
 np.int32(-13),
 np.int32(-19),
 np.int32(-10),
 np.int32(-9)]

In [60]:
# Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
arr4WithoutNegatives = np.where(arr4 < 0, 0, arr4)
arr4WithoutNegatives

array([ 0, 19,  0,  0,  0,  6,  2, 17, 12,  0, 20,  0,  0,  7,  0],
      dtype=int32)

In [63]:
# Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.
arr4SumOfZeroEllements = np.sum(arr4WithoutNegatives == 0)
arr4SumOfZeroEllements

np.int64(8)

## Завдання 5

- Запитайте в користувача довжину масивів.
- Створіть два одновимірні масиви вказаної довжини:
    - перший заповніть випадковими числами від 0 до 10;
    - другий заповніть випадковими числами від 10 до 20.
- Виведіть обидва вихідні масиви.
- Об'єднайте масиви в один і виведіть результат.
- Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.

In [66]:
# Запитайте в користувача довжину масивів.
arr5len = int(input("Enter array5 length:"))
arr6len = int(input("Enter array6 length:"))

Enter array5 length: 15
Enter array6 length: 20


In [68]:
# Створіть два одновимірні масиви вказаної довжини:
#     перший заповніть випадковими числами від 0 до 10;
#     другий заповніть випадковими числами від 10 до 20.
arr5 = np.random.randint(0, 11, size=arr5len)
arr6 = np.random.randint(10, 21, size=arr6len)
print(arr5)
print(arr6)

[ 5  5  3  1  9  1  8  6  8 10  4  5  5  6  1]
[16 13 19 19 16 10 17 14 19 16 14 16 14 12 20 16 14 17 14 20]


In [72]:
# Об'єднайте масиви в один і виведіть результат.
arr5 = np.append(arr5, arr6)
arr5

array([ 5,  5,  3,  1,  9,  1,  8,  6,  8, 10,  4,  5,  5,  6,  1, 16, 13,
       19, 19, 16, 10, 17, 14, 19, 16, 14, 16, 14, 12, 20, 16, 14, 17, 14,
       20], dtype=int32)

In [78]:
# Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.
n = min(len(arr5), len(arr6))

arrsSum = arr5.copy()
arrsDifference = arr5.copy()

arrsSum[:n] = arr5[:n] + arr6[:n]
arrsDifference[:n] = arr5[:n] - arr6[:n]
print("arr5 and arr6 sum", arrsSum)
print("arr5 and arr6 difference", arrsDifference)

arr5 and arr6 sum [21 18 22 20 25 11 25 20 27 26 18 21 19 18 21 32 27 36 33 36 10 17 14 19
 16 14 16 14 12 20 16 14 17 14 20]
arr5 and arr6 difference [-11  -8 -16 -18  -7  -9  -9  -8 -11  -6 -10 -11  -9  -6 -19   0  -1   2
   5  -4  10  17  14  19  16  14  16  14  12  20  16  14  17  14  20]


## Завдання 6

- Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
- Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
- Виведіть вихідну матрицю.
- Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
- Виведіть отриману матрицю.
- Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
- Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [80]:
# Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
matrixCols = int(input("Enter matrix Cols count:"))
matrixRows = int(input("Enter matrix Rows count:"))

Enter matrix Cols count: 4
Enter matrix Rows count: 6


In [85]:
# Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
# Виведіть вихідну матрицю.
arr7 = np.arange(1, matrixRows * matrixCols + 1).reshape(matrixRows, matrixCols)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [86]:
# Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
# Виведіть отриману матрицю.
matrixCols = int(input("Enter matrix Cols count:"))
matrixRows = int(input("Enter matrix Rows count:"))
arr7 = arr7.reshape(matrixRows, matrixCols)
arr7

Enter matrix Cols count: 2
Enter matrix Rows count: 12


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [88]:
# Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
print(np.max(arr7, axis=1))
print(np.min(arr7, axis=1))

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [91]:
# Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.
print(np.sum(arr7))

300
