# NumPy
*pip install numpy*

Пакет для математичних типів даних (векторів, матриць) та мат. операцій з ними

In [1]:
import numpy as np

## Завдання 1
Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.

- Збережіть масив у змінну і виведіть його на екран.
- Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
- Відсортуйте масив за зростанням і виведіть результат.
- Відобразіть масив до і після сортування.

In [2]:
arr1 = np.random.randint(0, 100, size=10)
print(arr1)

[96 72  6  9 25 57 85 69 83 22]


In [3]:
print("min = %d, max = %d, avg = %.1f" % (np.min(arr1), np.max(arr1), np.mean(arr1) ))

min = 6, max = 96, avg = 52.4


In [5]:
print(arr1)
print(np.sort(arr1))
print(arr1) # Висоновок масив не змінюється, створюється копія

[96 72  6  9 25 57 85 69 83 22]
[ 6  9 22 25 57 69 72 83 85 96]
[96 72  6  9 25 57 85 69 83 22]


# Завдання 2
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.

- Виведіть масив у читабельному вигляді (у вигляді таблиці).
- Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
- Визначте загальне середнє значення масиву.
- Виведіть усі результати в зручному вигляді (наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
arr2 = np.random.randint(1, 50, size=(4,4))

In [10]:
# Виведіть масив у читабельному вигляді (у вигляді таблиці).

In [11]:
print(arr2)

[[38 19 14  4]
 [13  2 45 14]
 [ 3 25 46 17]
 [18 47 24 19]]


In [9]:
print(*(a for a in arr2), sep='\n')

[38 19 14  4]
[13  2 45 14]
[ 3 25 46 17]
[18 47 24 19]


In [13]:
# Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
print(np.sum(arr2, axis=0)) # axis=0 - За стовпчиками 
print(np.sum(arr2, axis=1)) # axis=1 - ЗА рядками 

[ 72  93 129  54]
[ 75  74  91 108]


In [20]:
# zip(arr1,arr2) - поєднує множини за принципом [ [arr1[0], arr2[0]], [arr1[1], arr2[1]], ... ]
# map(fun, arr) - застосовує функцію fun до кожного елемента arr
# " ".join(arr) - поєднує всі елементи arr через пробіл (вимагає, щоб елементи arr були рядками)

print(
    *( f"{x} | {y}" for x, y in zip( arr2, np.sum(arr2, axis=1) ) ),
    "----------------",
    # f"{np.sum(arr2, axis=0)} {np.mean(arr2)}",
    " ".join(map(str, (np.sum(arr2, axis=0), "|", np.mean(arr2)))),
    sep='\n'

)

[38 19 14  4] | 75
[13  2 45 14] | 74
[ 3 25 46 17] | 91
[18 47 24 19] | 108
----------------
[ 72  93 129  54] | 21.75


<hr/>
# Завдання 3
Створіть масив розміром 3×5, заповнений числами від 0 до 14.

- Виведіть вихідний масив.
- Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
- Застосуйте операцію reshape, щоб отримати масив 5×3.
- Відобразіть результати на екран.

In [22]:
arr3 = np.random.randint(1, 14, size=(3,5))
print(arr3)

[[ 6  1  9  1 10]
 [ 3  4 11  7  9]
 [ 3  9 12 12  1]]


In [24]:
# Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
np.transpose(arr3)

array([[ 6,  3,  3],
       [ 1,  4,  9],
       [ 9, 11, 12],
       [ 1,  7, 12],
       [10,  9,  1]], dtype=int32)

In [28]:
# Застосуйте операцію reshape, щоб отримати масив 5×3.
np.reshape(arr3, shape=(5,3)) # реорганізація до нової форми, без збереження логіки розподілу

array([[ 6,  1,  9],
       [ 1, 10,  3],
       [ 4, 11,  7],
       [ 9,  3,  9],
       [12, 12,  1]], dtype=int32)

In [31]:
print(arr1)
np.reshape(arr1, shape=(-1,1)) # особливий варіант - створення "обгортки" для елементів масиву

[96 72  6  9 25 57 85 69 83 22]


array([[96],
       [72],
       [ 6],
       [ 9],
       [25],
       [57],
       [85],
       [69],
       [83],
       [22]], dtype=int32)

# Завдання 4
Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.

- Знайдіть мінімальне та максимальне значення в усьому масиві.
- Визначте індекси мінімального та максимального елементів (наприклад: (рядок, стовпець)).
- Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [34]:
arr4 = np.random.rand(10,10)
# print(*(f"{x:.3f}" for a in arr4 for x in a))
print(*(' '.join(f"{x:.3f}" for x in a) for a in arr4), sep='\n')

# ' '.join(f"{x:.3f}" for x in arr4[0])

0.483 0.982 0.765 0.141 0.662 0.307 0.564 0.862 0.668 0.077
0.821 0.902 0.705 0.232 0.703 0.478 0.027 0.250 0.977 0.749
0.154 0.364 0.486 0.235 0.571 0.903 0.260 0.940 0.401 0.482
0.637 0.026 0.195 0.748 0.366 0.660 0.362 0.786 0.058 0.950
0.551 0.089 0.436 0.964 0.315 0.701 0.116 0.651 0.399 0.730
0.702 0.211 0.701 0.059 0.060 0.080 0.746 0.371 0.870 0.907
0.964 0.137 0.134 0.476 0.100 0.471 0.085 0.538 0.306 0.968
0.346 0.986 0.470 0.796 0.579 0.334 0.443 0.770 0.333 0.728
0.211 0.317 0.347 0.347 0.229 0.754 0.497 0.063 0.173 0.627
0.494 0.995 0.816 0.622 0.337 0.934 0.821 0.101 0.821 0.907


In [44]:
# Визначте індекси мінімального та максимального елементів (наприклад: (рядок, стовпець)).
min_index = np.argmin(arr4)
print(min_index)
max_index = np.argmax(arr4)
max_index

31


np.int64(91)

In [45]:
xy = np.unravel_index(min_index, arr4.shape)
print("мінімальний елемент знаходиться за індексами:", ",".join(map(str, xy)))
xy2 = np.unravel_index(max_index, arr4.shape)
print("максимальний елемент знаходиться за індексами:", ",".join(map(str, xy2)))

мінімальний елемент знаходиться за індексами: 3,1
максимальний елемент знаходиться за індексами: 9,1


# Завдання 5
Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.

- Виведіть масив.
- За допомогою булевої індексації виберіть тільки додатні елементи.
- За допомогою булевої індексації виберіть тільки парні елементи.
- Виведіть обидва результати на екран.

In [50]:
arr5 = np.random.randint(-10, 10, size=15)
print(arr5)

[-2 -3  3 -5 -8  9  2  5  8 -8 -6  0 -5  6  6]


In [52]:
cond_index = arr5 > 0
print(cond_index)
print(arr5[cond_index])

[False False  True False False  True  True  True  True False False False
 False  True  True]
[3 9 2 5 8 6 6]


In [53]:
print(arr5[arr5 % 2 == 0]) #

[-2 -8  2  8 -8 -6  0  6  6]


In [54]:
np.count_nonzero(arr5 % 2 == 0) # підрахунок кількості елементів, що відповідають умові

np.int64(9)